on :
  push :
    branch :
      -main

jobs :
  build :
    name : build app
    runs-on : ubuntu-latest
    steps : 
      - name : menampilkan test
        run : echo "ini step build"

  test :
    name : test app
    runs-on : ubuntu-latest
    needs : build
    steps : 
      - name : menampilkan test
        run : echo "ini step test"
   
  deployment :
    name : deploy app
    runs-on : ubuntu-latest
    needs : test
    steps : 
      - name : menampilkan deploy
        run : echo "ini step deploy"

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            sudo rm -rf /var/www/html/*
            sudo rm -rf /var/www/html/.git
            sudo rm -rf /var/www/html/.github
            sudo gitclone https://github.com/lazuto123/HeroBiz /var/www/html
                     
